language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    #- os: osx
    #  sudo: required

addons:
  apt:
    packages:
      - git
      - cmake
      - pkg-config
      - libopencv-dev
      - xawtv
      - libyaml-cpp-dev
      - libboost-all-dev

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
